// Lain's palette
// Each color is a whisper from the Navi
const p = {
  // Deep space base
  black:       '#0A0A14',
  darkPurple:  '#16122A',
  purple:      '#2A2442',
  lightPurple: '#6A4E9B',
  ghostWhite:  '#F0EDF5',
  
  // Accents – glowing and deliberate
  crtGreen:    '#5EFFB8',
  bloodRed:    '#FF6B6B',
  darkRed:     '#A63E3E',
  gray:        '#7F8C8D',
  lightGray:   '#C0C7C9',
  almostWhite: '#F7F9FC',
  deepBlue:    '#1E1A2F',
  
  // High contrast – maximum signal
  hcYellow:    '#FFD966',
  hcPink:      '#FF99CC',
  hcRed:       '#FF6B6B',
  hcGreen:     '#66FFCC'
};

// ---- Dark theme: neon whispers on obsidian ----
const darkUi = {
  // Editor
  'editor.background':                     p.black,
  'editor.foreground':                     p.lightGray,
  'editor.inactiveSelectionBackground':    p.darkPurple + '66',
  'list.inactiveSelectionBackground':      p.purple + 'CC',
  'editor.selectionBackground':            p.purple + 'CC',   // 80% opacity
  'list.activeSelectionBackground':        p.purple + 'CC',   // same
  'editor.findMatchBackground':            p.bloodRed + '44',
  'editor.findMatchHighlightBackground':   p.darkRed + '66',
  'editor.lineNumber.foreground':          '#9B7BC9', 
  'editor.lineNumber.activeForeground':    p.crtGreen,
  'editorCursor.foreground':               p.crtGreen,
  'editorWhitespace.foreground':           p.purple + '66',
  'editorIndentGuide.background':          p.purple + '33',
  'editorIndentGuide.activeBackground':    p.lightPurple,
  'editorBracketMatch.background':         p.purple,
  'editorBracketMatch.border':             p.bloodRed,
  'editorGutter.background':               p.black,
  'editorError.foreground':                p.bloodRed,
  'editorWarning.foreground':              p.crtGreen,
  'editorInfo.foreground':                 p.lightPurple,
  'editorHint.foreground':                 p.gray,
  'editorOverviewRuler.errorForeground':   p.bloodRed,
  'editorOverviewRuler.warningForeground': p.crtGreen,
  'editorOverviewRuler.infoForeground':    p.lightPurple,
  'editorOverviewRuler.bracketMatchForeground': p.purple,
  
  // Widgets & Hovers
  'editorWidget.background':               p.darkPurple,
  'editorWidget.foreground':               p.lightGray,
  'editorWidget.border':                   p.purple,
  'editorHoverWidget.background':          p.darkPurple,
  'editorHoverWidget.foreground':          p.lightGray,
  'editorHoverWidget.border':              p.purple,
  'editorSuggestWidget.background':        p.darkPurple,
  'editorSuggestWidget.foreground':        p.lightGray,
  'editorSuggestWidget.selectedBackground': p.purple,
  'editorSuggestWidget.border':            p.purple,
  'editorLink.activeForeground':           p.crtGreen,
  
  // Diff
  'diffEditor.insertedTextBackground':     p.crtGreen + '33',
  'diffEditor.removedTextBackground':      p.bloodRed + '33',
  'diffEditor.border':                     p.purple,
  
  // Lists (sidebar, suggestions)
  'list.activeSelectionBackground':        p.purple,
  'list.activeSelectionForeground':        p.ghostWhite,
  'list.inactiveSelectionBackground':      p.darkPurple,
  'list.inactiveSelectionForeground':      p.lightGray,
  'list.hoverBackground':                  p.darkPurple + 'CC',
  'list.hoverForeground':                  p.crtGreen,
  'list.focusBackground':                  p.purple,
  'list.focusForeground':                  p.ghostWhite,
  'list.highlightForeground':              p.crtGreen,
  'list.errorForeground':                  p.bloodRed,
  'list.warningForeground':                p.crtGreen,
  
  // Activity Bar (left side)
  'activityBar.background':                p.black,
  'activityBar.foreground':                p.lightGray,
  'activityBar.inactiveForeground':        p.gray,
  'activityBar.border':                    p.darkPurple,
  'activityBarBadge.background':           p.bloodRed,
  'activityBarBadge.foreground':           p.ghostWhite,
  
  // Sidebar
  'sideBar.background':                    p.black,
  'sideBar.foreground':                    p.lightGray,
  'sideBar.border':                        p.darkPurple,
  'sideBarTitle.foreground':               p.crtGreen,
  'sideBarSectionHeader.background':       p.darkPurple,
  'sideBarSectionHeader.foreground':       p.lightGray,
  'sideBarSectionHeader.border':           p.purple,
  
  // Status Bar
  'statusBar.background':                  p.black,
  'statusBar.foreground':                  p.lightGray,
  'statusBar.border':                      p.darkPurple,
  'statusBar.noFolderBackground':          p.black,
  'statusBar.debuggingBackground':         p.bloodRed,
  'statusBar.debuggingForeground':         p.ghostWhite,
  'statusBarItem.prominentBackground':     p.purple,
  'statusBarItem.prominentHoverBackground':p.lightPurple,
  
  // Title Bar
  'titleBar.activeBackground':             p.black,
  'titleBar.activeForeground':             p.lightGray,
  'titleBar.inactiveBackground':           p.black,
  'titleBar.inactiveForeground':           p.gray,
  'titleBar.border':                       p.darkPurple,
  
  // Menus
  'menubar.selectionBackground':           p.purple,
  'menubar.selectionForeground':           p.ghostWhite,
  'menu.background':                       p.black,
  'menu.foreground':                       p.lightGray,
  'menu.selectionBackground':              p.purple,
  'menu.selectionForeground':              p.ghostWhite,
  'menu.separatorBackground':              p.darkPurple,
  
  // Panel (terminal, output)
  'panel.background':                      p.black,
  'panel.foreground':                      p.lightGray,
  'panel.border':                          p.darkPurple,
  'panelTitle.activeForeground':           p.crtGreen,
  'panelTitle.inactiveForeground':         p.gray,
  
  // Inputs
  'input.background':                      p.darkPurple,
  'input.foreground':                      p.lightGray,
  'input.border':                          p.purple,
  'input.placeholderForeground':           p.gray,
  'inputOption.activeBackground':          p.purple,
  'inputOption.activeBorder':              p.bloodRed,
  'inputValidation.errorBackground':       p.bloodRed,
  'inputValidation.errorForeground':       p.ghostWhite,
  'inputValidation.errorBorder':           p.bloodRed,
  'inputValidation.warningBackground':     p.crtGreen,
  'inputValidation.warningForeground':     p.black,
  'inputValidation.warningBorder':         p.crtGreen,
  'inputValidation.infoBackground':        p.lightPurple,
  'inputValidation.infoForeground':        p.ghostWhite,
  'inputValidation.infoBorder':            p.lightPurple,
  
  // Scrollbar
  'scrollbar.shadow':                      p.black,
  'scrollbarSlider.background':            p.purple + '88',
  'scrollbarSlider.hoverBackground':       p.lightPurple + 'AA',
  'scrollbarSlider.activeBackground':      p.bloodRed,
  
  // Badges & Progress
  'badge.background':                      p.bloodRed,
  'badge.foreground':                      p.ghostWhite,
  'progressBar.background':                p.crtGreen,
  
  // Notifications
  'notificationCenterHeader.background':   p.darkPurple,
  'notificationCenterHeader.foreground':   p.lightGray,
  'notificationToast.border':              p.purple,
  'notifications.background':              p.darkPurple,
  'notifications.foreground':              p.lightGray,
  'notifications.border':                  p.purple,
  
  // Extensions
  'extensionButton.prominentBackground':       p.bloodRed,
  'extensionButton.prominentForeground':       p.ghostWhite,
  'extensionButton.prominentHoverBackground':  p.darkRed,
  
  // Picker groups
  'pickerGroup.foreground':                p.crtGreen,
  'pickerGroup.border':                    p.darkPurple,
  
  // Terminal – ansi colors stay true to the palette
  'terminal.background':                   p.black,
  'terminal.foreground':                   p.lightGray,
  'terminal.ansiBlack':                    p.black,
  'terminal.ansiRed':                      p.bloodRed,
  'terminal.ansiGreen':                    p.crtGreen,
  'terminal.ansiYellow':                   p.lightGray,
  'terminal.ansiBlue':                     p.lightPurple,
  'terminal.ansiMagenta':                  p.gray,
  'terminal.ansiCyan':                     p.purple,
  'terminal.ansiWhite':                    p.ghostWhite,
  'terminal.ansiBrightBlack':              p.darkPurple,
  'terminal.ansiBrightRed':                p.bloodRed,
  'terminal.ansiBrightGreen':              p.crtGreen,
  'terminal.ansiBrightYellow':             p.lightGray,
  'terminal.ansiBrightBlue':               p.lightPurple,
  'terminal.ansiBrightMagenta':            p.gray,
  'terminal.ansiBrightCyan':               p.purple,
  'terminal.ansiBrightWhite':              p.ghostWhite,
  
  // Git decorations
  'gitDecoration.addedResourceForeground':       p.crtGreen,
  'gitDecoration.modifiedResourceForeground':    p.lightPurple,
  'gitDecoration.deletedResourceForeground':     p.bloodRed,
  'gitDecoration.untrackedResourceForeground':   p.gray,
  'gitDecoration.ignoredResourceForeground':     p.purple,
  'gitDecoration.conflictingResourceForeground': p.bloodRed
};

const darkTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.gray, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: p.lightPurple } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: p.crtGreen } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: p.crtGreen } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: p.ghostWhite } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: p.lightPurple, fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.bloodRed } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: p.lightGray } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.bloodRed, background: p.darkPurple } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.gray, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: p.lightPurple } },
  { scope: ['markup.raw'], settings: { foreground: p.crtGreen } },
  { scope: ['meta.separator'], settings: { foreground: p.purple, fontStyle: 'bold' } }
];

// ---- Light theme: ethereal and soft ----
const lightUi = {
  'editor.background':                     '#FDF9FF',
  'editor.foreground':                     p.deepBlue,
  'list.inactiveSelectionBackground':      '#BFA0D6', 
  'editor.selectionBackground':            '#BFA0D6', 
  'list.activeSelectionBackground':        '#BFA0D6',
  'editor.findMatchBackground':            p.bloodRed + '44',
  'editor.findMatchHighlightBackground':   p.bloodRed + '88',
  'editor.lineNumber.foreground':          p.lightPurple,
  'editor.lineNumber.activeForeground':    '#3B8B3B',
  'editorCursor.foreground':               '#1F5A1F',  
  'editorWhitespace.foreground':           '#D9C5E6' + '88',
  'editorIndentGuide.background':          '#D9C5E6',
  'editorIndentGuide.activeBackground':    p.lightPurple,
  'editorBracketMatch.background':         '#D9C5E6',
  'editorBracketMatch.border':             p.bloodRed,
  'editorGutter.background':               '#FDF9FF',
  'editorError.foreground':                p.bloodRed,
  'editorWarning.foreground':              '#3B8B3B',
  'editorInfo.foreground':                 p.lightPurple,
  'editorHint.foreground':                 p.gray,
  'editorOverviewRuler.errorForeground':   p.bloodRed,
  'editorOverviewRuler.warningForeground': '#3B8B3B',
  'editorOverviewRuler.infoForeground':    p.lightPurple,
  'editorOverviewRuler.bracketMatchForeground': '#D9C5E6',
  'editorWidget.background':               '#FDF9FF',
  'editorWidget.foreground':               p.deepBlue,
  'editorWidget.border':                   '#D9C5E6',
  'editorHoverWidget.background':          '#FDF9FF',
  'editorHoverWidget.foreground':          p.deepBlue,
  'editorHoverWidget.border':              '#D9C5E6',
  'editorSuggestWidget.background':        '#FDF9FF',
  'editorSuggestWidget.foreground':        p.deepBlue,
  'editorSuggestWidget.selectedBackground':'#D9C5E6',
  'editorSuggestWidget.border':            '#D9C5E6',
  'editorLink.activeForeground':           '#3B8B3B',
  'diffEditor.insertedTextBackground':     '#3B8B3B33',
  'diffEditor.removedTextBackground':      p.bloodRed + '33',
  'diffEditor.border':                     '#D9C5E6',
  'list.activeSelectionBackground':        '#D9C5E6',
  'list.activeSelectionForeground':        p.deepBlue,
  'list.inactiveSelectionBackground':      '#D9C5E6',
  'list.inactiveSelectionForeground':      p.deepBlue,
  'list.hoverBackground':                  '#D9C5E6',
  'list.hoverForeground':                  p.deepBlue,
  'list.focusBackground':                  '#D9C5E6',
  'list.focusForeground':                  p.deepBlue,
  'list.highlightForeground':              '#3B8B3B',
  'list.errorForeground':                  p.bloodRed,
  'list.warningForeground':                '#3B8B3B',
  'activityBar.background':                '#FDF9FF',
  'activityBar.foreground':                p.deepBlue,
  'activityBar.inactiveForeground':        p.gray,
  'activityBar.border':                    '#D9C5E6',
  'activityBarBadge.background':           p.bloodRed,
  'activityBarBadge.foreground':           '#FDF9FF',
  'sideBar.background':                    '#FDF9FF',
  'sideBar.foreground':                    p.deepBlue,
  'sideBar.border':                        '#D9C5E6',
  'sideBarTitle.foreground':               '#3B8B3B',
  'sideBarSectionHeader.background':       '#FDF9FF',
  'sideBarSectionHeader.foreground':       p.deepBlue,
  'sideBarSectionHeader.border':           '#D9C5E6',
  'statusBar.background':                  '#FDF9FF',
  'statusBar.foreground':                  p.deepBlue,
  'statusBar.border':                      '#D9C5E6',
  'statusBar.noFolderBackground':          '#FDF9FF',
  'statusBar.debuggingBackground':         p.bloodRed,
  'statusBar.debuggingForeground':         '#FDF9FF',
  'statusBarItem.prominentBackground':     '#D9C5E6',
  'statusBarItem.prominentHoverBackground':p.lightPurple,
  'titleBar.activeBackground':             '#FDF9FF',
  'titleBar.activeForeground':             p.deepBlue,
  'titleBar.inactiveBackground':           '#FDF9FF',
  'titleBar.inactiveForeground':           p.gray,
  'titleBar.border':                       '#D9C5E6',
  'menubar.selectionBackground':           '#D9C5E6',
  'menubar.selectionForeground':           p.deepBlue,
  'menu.background':                       '#FDF9FF',
  'menu.foreground':                       p.deepBlue,
  'menu.selectionBackground':              '#D9C5E6',
  'menu.selectionForeground':              p.deepBlue,
  'menu.separatorBackground':              '#D9C5E6',
  'panel.background':                      '#FDF9FF',
  'panel.foreground':                      p.deepBlue,
  'panel.border':                          '#D9C5E6',
  'panelTitle.activeForeground':           '#3B8B3B',
  'panelTitle.inactiveForeground':         p.gray,
  'input.background':                      '#FDF9FF',
  'input.foreground':                      p.deepBlue,
  'input.border':                          '#D9C5E6',
  'input.placeholderForeground':           p.gray,
  'inputOption.activeBackground':          '#D9C5E6',
  'inputOption.activeBorder':              p.bloodRed,
  'inputValidation.errorBackground':       p.bloodRed,
  'inputValidation.errorForeground':       '#FDF9FF',
  'inputValidation.errorBorder':           p.bloodRed,
  'inputValidation.warningBackground':     '#3B8B3B',
  'inputValidation.warningForeground':     '#FDF9FF',
  'inputValidation.warningBorder':         '#3B8B3B',
  'inputValidation.infoBackground':        p.lightPurple,
  'inputValidation.infoForeground':        '#FDF9FF',
  'inputValidation.infoBorder':            p.lightPurple,
  'scrollbar.shadow':                      '#FDF9FF',
  'scrollbarSlider.background':            '#D9C5E6' + '88',
  'scrollbarSlider.hoverBackground':       p.lightPurple + 'AA',
  'scrollbarSlider.activeBackground':      p.bloodRed,
  'badge.background':                      p.bloodRed,
  'badge.foreground':                      '#FDF9FF',
  'progressBar.background':                '#3B8B3B',
  'notificationCenterHeader.background':   '#FDF9FF',
  'notificationCenterHeader.foreground':   p.deepBlue,
  'notificationToast.border':              '#D9C5E6',
  'notifications.background':              '#FDF9FF',
  'notifications.foreground':              p.deepBlue,
  'notifications.border':                  '#D9C5E6',
  'extensionButton.prominentBackground':       p.bloodRed,
  'extensionButton.prominentForeground':       '#FDF9FF',
  'extensionButton.prominentHoverBackground':  p.darkRed,
  'pickerGroup.foreground':                '#3B8B3B',
  'pickerGroup.border':                    '#D9C5E6',
  'terminal.background':                   '#FDF9FF',
  'terminal.foreground':                   p.deepBlue,
  'terminal.ansiBlack':                    p.black,
  'terminal.ansiRed':                      p.bloodRed,
  'terminal.ansiGreen':                    '#3B8B3B',
  'terminal.ansiYellow':                   p.lightGray,
  'terminal.ansiBlue':                     p.lightPurple,
  'terminal.ansiMagenta':                  p.gray,
  'terminal.ansiCyan':                     p.purple,
  'terminal.ansiWhite':                    p.ghostWhite,
  'terminal.ansiBrightBlack':              p.darkPurple,
  'terminal.ansiBrightRed':                p.bloodRed,
  'terminal.ansiBrightGreen':              '#3B8B3B',
  'terminal.ansiBrightYellow':             p.lightGray,
  'terminal.ansiBrightBlue':               p.lightPurple,
  'terminal.ansiBrightMagenta':            p.gray,
  'terminal.ansiBrightCyan':               p.purple,
  'terminal.ansiBrightWhite':              p.ghostWhite,
  'gitDecoration.addedResourceForeground':       '#3B8B3B',
  'gitDecoration.modifiedResourceForeground':    p.lightPurple,
  'gitDecoration.deletedResourceForeground':     p.bloodRed,
  'gitDecoration.untrackedResourceForeground':   p.gray,
  'gitDecoration.ignoredResourceForeground':     '#D9C5E6',
  'gitDecoration.conflictingResourceForeground': p.bloodRed
};

const lightTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.gray, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: p.lightPurple } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: '#3B8B3B' } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: '#3B8B3B' } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: p.deepBlue } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: p.lightPurple, fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.bloodRed } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: p.deepBlue } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.bloodRed, background: '#FDF9FF' } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.gray, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: p.lightPurple } },
  { scope: ['markup.raw'], settings: { foreground: '#3B8B3B' } },
  { scope: ['meta.separator'], settings: { foreground: '#D9C5E6', fontStyle: 'bold' } }
];

// ---- High Contrast: pure signal ----
const hcUi = {
  'editor.background':                     '#000000',
  'editor.foreground':                     '#FFFFFF',
  'editor.inactiveSelectionBackground':    p.hcYellow + '66',
  'editor.selectionBackground':            p.hcYellow,
  'editor.selectionHighlightBackground':   p.hcPink + '66',
  'editor.findMatchBackground':            p.hcRed,
  'editor.findMatchHighlightBackground':   p.hcRed + '88',
  'editor.lineNumber.foreground':          p.hcPink,
  'editor.lineNumber.activeForeground':    p.hcGreen,
  'editorCursor.foreground':               p.hcGreen,
  'editorWhitespace.foreground':           p.hcYellow + '88',
  'editorIndentGuide.background':          p.hcYellow,
  'editorIndentGuide.activeBackground':    p.hcPink,
  'editorBracketMatch.background':         p.hcYellow,
  'editorBracketMatch.border':             p.hcRed,
  'editorGutter.background':               '#000000',
  'editorError.foreground':                p.hcRed,
  'editorWarning.foreground':              p.hcGreen,
  'editorInfo.foreground':                 p.hcPink,
  'editorHint.foreground':                 p.lightGray,
  'editorOverviewRuler.errorForeground':   p.hcRed,
  'editorOverviewRuler.warningForeground': p.hcGreen,
  'editorOverviewRuler.infoForeground':    p.hcPink,
  'editorOverviewRuler.bracketMatchForeground': p.hcYellow,
  'editorWidget.background':               '#000000',
  'editorWidget.foreground':               '#FFFFFF',
  'editorWidget.border':                   p.hcYellow,
  'editorHoverWidget.background':          '#000000',
  'editorHoverWidget.foreground':          '#FFFFFF',
  'editorHoverWidget.border':              p.hcYellow,
  'editorSuggestWidget.background':        '#000000',
  'editorSuggestWidget.foreground':        '#FFFFFF',
  'editorSuggestWidget.selectedBackground':p.hcYellow,
  'editorSuggestWidget.border':            p.hcYellow,
  'editorLink.activeForeground':           p.hcGreen,
  'diffEditor.insertedTextBackground':     p.hcGreen + '33',
  'diffEditor.removedTextBackground':      p.hcRed + '33',
  'diffEditor.border':                     p.hcYellow,
  'list.activeSelectionBackground':        p.hcYellow,
  'list.activeSelectionForeground':        '#000000',
  'list.inactiveSelectionBackground':      p.hcYellow,
  'list.inactiveSelectionForeground':      '#000000',
  'list.hoverBackground':                  p.hcYellow,
  'list.hoverForeground':                  '#000000',
  'list.focusBackground':                  p.hcYellow,
  'list.focusForeground':                  '#000000',
  'list.highlightForeground':              p.hcGreen,
  'list.errorForeground':                  p.hcRed,
  'list.warningForeground':                p.hcGreen,
  'activityBar.background':                '#000000',
  'activityBar.foreground':                '#FFFFFF',
  'activityBar.inactiveForeground':        p.lightGray,
  'activityBar.border':                    p.hcYellow,
  'activityBarBadge.background':           p.hcRed,
  'activityBarBadge.foreground':           '#000000',
  'sideBar.background':                    '#000000',
  'sideBar.foreground':                    '#FFFFFF',
  'sideBar.border':                        p.hcYellow,
  'sideBarTitle.foreground':               p.hcGreen,
  'sideBarSectionHeader.background':       '#000000',
  'sideBarSectionHeader.foreground':       '#FFFFFF',
  'sideBarSectionHeader.border':           p.hcYellow,
  'statusBar.background':                  '#000000',
  'statusBar.foreground':                  '#FFFFFF',
  'statusBar.border':                      p.hcYellow,
  'statusBar.noFolderBackground':          '#000000',
  'statusBar.debuggingBackground':         p.hcRed,
  'statusBar.debuggingForeground':         '#000000',
  'statusBarItem.prominentBackground':     p.hcYellow,
  'statusBarItem.prominentHoverBackground':p.hcPink,
  'titleBar.activeBackground':             '#000000',
  'titleBar.activeForeground':             '#FFFFFF',
  'titleBar.inactiveBackground':           '#000000',
  'titleBar.inactiveForeground':           p.lightGray,
  'titleBar.border':                       p.hcYellow,
  'menubar.selectionBackground':           p.hcYellow,
  'menubar.selectionForeground':           '#000000',
  'menu.background':                       '#000000',
  'menu.foreground':                       '#FFFFFF',
  'menu.selectionBackground':              p.hcYellow,
  'menu.selectionForeground':              '#000000',
  'menu.separatorBackground':              p.hcYellow,
  'panel.background':                      '#000000',
  'panel.foreground':                      '#FFFFFF',
  'panel.border':                          p.hcYellow,
  'panelTitle.activeForeground':           p.hcGreen,
  'panelTitle.inactiveForeground':         p.lightGray,
  'input.background':                      '#000000',
  'input.foreground':                      '#FFFFFF',
  'input.border':                          p.hcYellow,
  'input.placeholderForeground':           p.lightGray,
  'inputOption.activeBackground':          p.hcYellow,
  'inputOption.activeBorder':              p.hcRed,
  'inputValidation.errorBackground':       p.hcRed,
  'inputValidation.errorForeground':       '#000000',
  'inputValidation.errorBorder':           p.hcRed,
  'inputValidation.warningBackground':     p.hcGreen,
  'inputValidation.warningForeground':     '#000000',
  'inputValidation.warningBorder':         p.hcGreen,
  'inputValidation.infoBackground':        p.hcPink,
  'inputValidation.infoForeground':        '#000000',
  'inputValidation.infoBorder':            p.hcPink,
  'scrollbar.shadow':                      '#000000',
  'scrollbarSlider.background':            p.hcYellow + '88',
  'scrollbarSlider.hoverBackground':       p.hcPink + 'AA',
  'scrollbarSlider.activeBackground':      p.hcRed,
  'badge.background':                      p.hcRed,
  'badge.foreground':                      '#000000',
  'progressBar.background':                p.hcGreen,
  'notificationCenterHeader.background':   '#000000',
  'notificationCenterHeader.foreground':   '#FFFFFF',
  'notificationToast.border':              p.hcYellow,
  'notifications.background':              '#000000',
  'notifications.foreground':              '#FFFFFF',
  'notifications.border':                  p.hcYellow,
  'extensionButton.prominentBackground':       p.hcRed,
  'extensionButton.prominentForeground':       '#000000',
  'extensionButton.prominentHoverBackground':  p.hcRed,
  'pickerGroup.foreground':                p.hcGreen,
  'pickerGroup.border':                    p.hcYellow,
  'terminal.background':                   '#000000',
  'terminal.foreground':                   '#FFFFFF',
  'terminal.ansiBlack':                    '#000000',
  'terminal.ansiRed':                      p.hcRed,
  'terminal.ansiGreen':                    p.hcGreen,
  'terminal.ansiYellow':                   p.hcYellow,
  'terminal.ansiBlue':                     p.hcPink,
  'terminal.ansiMagenta':                  p.lightGray,
  'terminal.ansiCyan':                     p.hcYellow,
  'terminal.ansiWhite':                    '#FFFFFF',
  'terminal.ansiBrightBlack':              '#000000',
  'terminal.ansiBrightRed':                p.hcRed,
  'terminal.ansiBrightGreen':              p.hcGreen,
  'terminal.ansiBrightYellow':             p.hcYellow,
  'terminal.ansiBrightBlue':               p.hcPink,
  'terminal.ansiBrightMagenta':            p.lightGray,
  'terminal.ansiBrightCyan':               p.hcYellow,
  'terminal.ansiBrightWhite':              '#FFFFFF',
  'gitDecoration.addedResourceForeground':       p.hcGreen,
  'gitDecoration.modifiedResourceForeground':    p.hcPink,
  'gitDecoration.deletedResourceForeground':     p.hcRed,
  'gitDecoration.untrackedResourceForeground':   p.lightGray,
  'gitDecoration.ignoredResourceForeground':     p.hcYellow,
  'gitDecoration.conflictingResourceForeground': p.hcRed
};

const hcTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.lightGray, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: p.hcPink } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: p.hcGreen } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.hcRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: p.hcGreen } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: '#FFFFFF' } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: p.hcPink, fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.hcRed } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: '#FFFFFF' } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.hcRed, background: '#000000' } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.hcRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.lightGray, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: p.hcPink } },
  { scope: ['markup.raw'], settings: { foreground: p.hcGreen } },
  { scope: ['meta.separator'], settings: { foreground: p.hcYellow, fontStyle: 'bold' } }
];

module.exports = {
  dark:  { ui: darkUi, tokens: darkTokens },
  light: { ui: lightUi, tokens: lightTokens },
  highContrast: { ui: hcUi, tokens: hcTokens }
};
