const p = {
  // —— base ——
  voidBlack:      '#050508',
  deepAbyss:      '#0A0A14',
  darkRealm:      '#12101E',
  shadowPurple:   '#1C1830',
  mutedPurple:    '#2A2445',
  royalPurple:    '#3B2E5E',
  paleLavender:   '#7B6B9E',
  ghostWhite:     '#F0EDF5',
  
  // —— functional grays ——
  smoke:          '#8A8A9E',
  silver:         '#B4B4C4',
  lightGray:      '#D1D1E0',
  offWhite:       '#F5F5FA',
  
  // —— accents ——
  neonCyan:       '#4EFFE6',
  crtGreen:       '#5EFFB8',
  deepGreen:      '#2EAA7A',
  bloodRed:       '#FF5A6E',
  darkRed:        '#A83C3C',
  warningOrange:  '#FFB347',
  infoBlue:       '#5E9EFF',
  
  // —— high contrast ——
  hcYellow:       '#FFE066',
  hcPink:         '#FF99CC',
  hcRed:          '#FF6B6B',
  hcGreen:        '#66FFCC',
  hcCyan:         '#66FFFF',
  
  // —— opacity helpers ——
  opacity: {
    transparent: '00',
    faint:       '22',
    light:       '44',
    medium:      '66',
    strong:      '88',
    solid:       'CC',
  }
};

const alpha = (color, level) => color + level;

// ---------- DARK THEME (fixed) ----------
const darkUi = {
  // editor base
  'editor.background':                     p.voidBlack,
  'editor.foreground':                     p.silver,
  'editor.inactiveSelectionBackground':    alpha(p.darkRealm, p.opacity.strong),
  'editor.selectionBackground':            '#8B6BB0',        // lighter for 3.0+ contrast
  'editor.selectionHighlightBackground':   alpha(p.paleLavender, p.opacity.light),
  'editor.findMatchBackground':            alpha(p.bloodRed, p.opacity.light),
  'editor.findMatchHighlightBackground':   alpha(p.darkRed, p.opacity.medium),
  'editor.findRangeHighlightBackground':   alpha(p.mutedPurple, p.opacity.medium),
  'editor.lineHighlightBackground':        alpha(p.darkRealm, p.opacity.strong),
  'editor.lineNumber.foreground':          '#C5A8D9',        // brighter for 4.5+ contrast
  'editor.lineNumber.activeForeground':    p.neonCyan,
  'editorCursor.foreground':               p.crtGreen,
  'editorCursor.background':               alpha(p.crtGreen, p.opacity.faint),
  'editorWhitespace.foreground':           alpha(p.mutedPurple, p.opacity.medium),
  'editorIndentGuide.background':          alpha(p.mutedPurple, p.opacity.light),
  'editorIndentGuide.activeBackground':    p.paleLavender,
  'editorBracketMatch.background':         alpha(p.royalPurple, p.opacity.solid),
  'editorBracketMatch.border':             p.bloodRed,
  'editorBracketHighlight.foreground1':    p.neonCyan,
  'editorBracketHighlight.foreground2':    p.crtGreen,
  'editorBracketHighlight.foreground3':    p.warningOrange,
  'editorBracketHighlight.foreground4':    p.paleLavender,
  'editorBracketHighlight.unexpectedBracket.foreground': p.bloodRed,
  'editorGutter.background':               p.voidBlack,
  'editorGutter.modifiedBackground':       alpha(p.infoBlue, p.opacity.medium),
  'editorGutter.addedBackground':          alpha(p.crtGreen, p.opacity.medium),
  'editorGutter.deletedBackground':        alpha(p.bloodRed, p.opacity.medium),
  'editorError.foreground':                p.bloodRed,
  'editorError.border':                    alpha(p.bloodRed, p.opacity.medium),
  'editorWarning.foreground':              p.warningOrange,
  'editorWarning.border':                  alpha(p.warningOrange, p.opacity.medium),
  'editorInfo.foreground':                 p.infoBlue,
  'editorInfo.border':                     alpha(p.infoBlue, p.opacity.medium),
  'editorHint.foreground':                 p.smoke,
  'editorOverviewRuler.errorForeground':   p.bloodRed,
  'editorOverviewRuler.warningForeground': p.warningOrange,
  'editorOverviewRuler.infoForeground':    p.infoBlue,
  'editorOverviewRuler.bracketMatchForeground': p.royalPurple,
  'editorOverviewRuler.modifiedForeground': alpha(p.infoBlue, p.opacity.strong),
  'editorOverviewRuler.addedForeground':   alpha(p.crtGreen, p.opacity.strong),
  'editorOverviewRuler.deletedForeground': alpha(p.bloodRed, p.opacity.strong),

  // widgets & hovers
  'editorWidget.background':               p.darkRealm,
  'editorWidget.foreground':               p.lightGray,
  'editorWidget.border':                   alpha(p.royalPurple, p.opacity.solid),
  'editorHoverWidget.background':          p.shadowPurple,
  'editorHoverWidget.foreground':          p.offWhite,
  'editorHoverWidget.border':              alpha(p.paleLavender, p.opacity.strong),
  'editorSuggestWidget.background':        p.darkRealm,
  'editorSuggestWidget.foreground':        p.silver,
  'editorSuggestWidget.selectedBackground': alpha(p.royalPurple, p.opacity.solid),
  'editorSuggestWidget.highlightForeground': p.crtGreen,
  'editorSuggestWidget.border':            alpha(p.mutedPurple, p.opacity.solid),
  'editorLink.activeForeground':           p.neonCyan,
  'editorLightBulb.foreground':            p.warningOrange,
  'editorLightBulbAutoFix.foreground':     p.crtGreen,

  // diff
  'diffEditor.insertedTextBackground':     alpha(p.crtGreen, p.opacity.light),
  'diffEditor.removedTextBackground':      alpha(p.bloodRed, p.opacity.light),
  'diffEditor.border':                     alpha(p.royalPurple, p.opacity.solid),
  'diffEditor.diagonalFill':               alpha(p.paleLavender, p.opacity.light),

  // lists (sidebar, quick pick)
  'list.activeSelectionBackground':        '#8B6BB0',        // match selection
  'list.activeSelectionForeground':        p.ghostWhite,
  'list.inactiveSelectionBackground':      alpha(p.shadowPurple, p.opacity.solid),
  'list.inactiveSelectionForeground':      p.silver,
  'list.hoverBackground':                  alpha(p.mutedPurple, p.opacity.strong),
  'list.hoverForeground':                  p.crtGreen,
  'list.focusBackground':                  alpha(p.royalPurple, p.opacity.solid),
  'list.focusForeground':                  p.ghostWhite,
  'list.highlightForeground':              p.crtGreen,
  'list.errorForeground':                  p.bloodRed,
  'list.warningForeground':                p.warningOrange,
  'listFilterWidget.background':           alpha(p.voidBlack, p.opacity.solid),
  'listFilterWidget.outline':              p.bloodRed,
  'listFilterWidget.noMatchesOutline':     p.bloodRed,

  // activity bar
  'activityBar.background':                p.voidBlack,
  'activityBar.foreground':                p.silver,
  'activityBar.inactiveForeground':        alpha(p.smoke, p.opacity.medium),
  'activityBar.border':                    alpha(p.darkRealm, p.opacity.solid),
  'activityBarBadge.background':           p.bloodRed,
  'activityBarBadge.foreground':           p.ghostWhite,
  'activityBar.activeBorder':              p.crtGreen,
  'activityBar.activeBackground':          alpha(p.darkRealm, p.opacity.solid),
  'activityBar.activeFocusBorder':         p.neonCyan,

  // sidebar
  'sideBar.background':                    p.voidBlack,
  'sideBar.foreground':                    p.lightGray,
  'sideBar.border':                        alpha(p.darkRealm, p.opacity.solid),
  'sideBarTitle.foreground':               p.neonCyan,
  'sideBarSectionHeader.background':       p.deepAbyss,
  'sideBarSectionHeader.foreground':       p.offWhite,
  'sideBarSectionHeader.border':           alpha(p.mutedPurple, p.opacity.solid),
  'sideBar.dropBackground':                alpha(p.royalPurple, p.opacity.medium),

  // status bar
  'statusBar.background':                  p.voidBlack,
  'statusBar.foreground':                  p.silver,
  'statusBar.border':                      alpha(p.darkRealm, p.opacity.solid),
  'statusBar.noFolderBackground':          p.voidBlack,
  'statusBar.debuggingBackground':         p.bloodRed,
  'statusBar.debuggingForeground':         p.ghostWhite,
  'statusBarItem.prominentBackground':     alpha(p.royalPurple, p.opacity.solid),
  'statusBarItem.prominentHoverBackground':alpha(p.paleLavender, p.opacity.solid),
  'statusBarItem.remoteBackground':        p.infoBlue,
  'statusBarItem.remoteForeground':        p.voidBlack,
  'statusBarItem.errorBackground':         p.bloodRed,
  'statusBarItem.errorForeground':         p.ghostWhite,

  // title bar
  'titleBar.activeBackground':             p.voidBlack,
  'titleBar.activeForeground':             p.lightGray,
  'titleBar.inactiveBackground':           p.voidBlack,
  'titleBar.inactiveForeground':           alpha(p.smoke, p.opacity.medium),
  'titleBar.border':                       alpha(p.darkRealm, p.opacity.solid),

  // menus
  'menubar.selectionBackground':           alpha(p.royalPurple, p.opacity.solid),
  'menubar.selectionForeground':           p.ghostWhite,
  'menu.background':                       p.voidBlack,
  'menu.foreground':                       p.silver,
  'menu.selectionBackground':              alpha(p.royalPurple, p.opacity.solid),
  'menu.selectionForeground':              p.ghostWhite,
  'menu.separatorBackground':              alpha(p.mutedPurple, p.opacity.solid),
  'menu.border':                           alpha(p.darkRealm, p.opacity.solid),

  // panel (terminal, output, problems)
  'panel.background':                      p.voidBlack,
  'panel.foreground':                      p.silver,
  'panel.border':                          alpha(p.darkRealm, p.opacity.solid),
  'panelTitle.activeForeground':           p.crtGreen,
  'panelTitle.activeBorder':               p.crtGreen,
  'panelTitle.inactiveForeground':         alpha(p.smoke, p.opacity.medium),
  'panelInput.border':                     alpha(p.mutedPurple, p.opacity.solid),
  'panelSectionHeader.background':         p.deepAbyss,
  'panelSectionHeader.foreground':         p.offWhite,
  'panelSectionHeader.border':             alpha(p.mutedPurple, p.opacity.solid),

  // inputs
  'input.background':                      p.shadowPurple,
  'input.foreground':                      p.lightGray,
  'input.border':                          alpha(p.royalPurple, p.opacity.solid),
  'input.placeholderForeground':           alpha(p.smoke, p.opacity.strong),
  'inputOption.activeBackground':          alpha(p.royalPurple, p.opacity.solid),
  'inputOption.activeBorder':              p.bloodRed,
  'inputOption.hoverBackground':           alpha(p.paleLavender, p.opacity.light),
  'inputValidation.errorBackground':       p.bloodRed,
  'inputValidation.errorForeground':       p.ghostWhite,
  'inputValidation.errorBorder':           p.bloodRed,
  'inputValidation.warningBackground':     p.warningOrange,
  'inputValidation.warningForeground':     p.voidBlack,
  'inputValidation.warningBorder':         p.warningOrange,
  'inputValidation.infoBackground':        p.infoBlue,
  'inputValidation.infoForeground':        p.voidBlack,
  'infoBorder': p.infoBlue,

  // scrollbar
  'scrollbar.shadow':                      p.voidBlack,
  'scrollbarSlider.background':            alpha(p.mutedPurple, p.opacity.medium),
  'scrollbarSlider.hoverBackground':       alpha(p.paleLavender, p.opacity.strong),
  'scrollbarSlider.activeBackground':      p.bloodRed,

  // badges & progress
  'badge.background':                      p.bloodRed,
  'badge.foreground':                      p.ghostWhite,
  'progressBar.background':                p.crtGreen,

  // notifications
  'notificationCenterHeader.background':   p.darkRealm,
  'notificationCenterHeader.foreground':   p.lightGray,
  'notificationToast.border':              alpha(p.royalPurple, p.opacity.solid),
  'notifications.background':              p.darkRealm,
  'notifications.foreground':              p.lightGray,
  'notifications.border':                  alpha(p.royalPurple, p.opacity.solid),
  'notificationsErrorIcon.foreground':     p.bloodRed,
  'notificationsWarningIcon.foreground':   p.warningOrange,
  'notificationsInfoIcon.foreground':      p.infoBlue,

  // extensions
  'extensionButton.prominentBackground':       p.bloodRed,
  'extensionButton.prominentForeground':       p.ghostWhite,
  'extensionButton.prominentHoverBackground':  p.darkRed,

  // picker groups
  'pickerGroup.foreground':                p.crtGreen,
  'pickerGroup.border':                    alpha(p.mutedPurple, p.opacity.solid),

  // terminal
  'terminal.background':                   p.voidBlack,
  'terminal.foreground':                   p.silver,
  'terminal.ansiBlack':                    p.voidBlack,
  'terminal.ansiRed':                      p.bloodRed,
  'terminal.ansiGreen':                    p.crtGreen,
  'terminal.ansiYellow':                   p.warningOrange,
  'terminal.ansiBlue':                     p.infoBlue,
  'terminal.ansiMagenta':                  p.paleLavender,
  'terminal.ansiCyan':                     p.neonCyan,
  'terminal.ansiWhite':                    p.offWhite,
  'terminal.ansiBrightBlack':              p.shadowPurple,
  'terminal.ansiBrightRed':                p.bloodRed,
  'terminal.ansiBrightGreen':              p.deepGreen,
  'terminal.ansiBrightYellow':             p.warningOrange,
  'terminal.ansiBrightBlue':               p.infoBlue,
  'terminal.ansiBrightMagenta':            p.royalPurple,
  'terminal.ansiBrightCyan':               p.neonCyan,
  'terminal.ansiBrightWhite':              p.ghostWhite,
  'terminal.selectionBackground':          alpha(p.royalPurple, p.opacity.solid),
  'terminal.dropBackground':               alpha(p.royalPurple, p.opacity.medium),

  // git decorations
  'gitDecoration.addedResourceForeground':       p.crtGreen,
  'gitDecoration.modifiedResourceForeground':    p.paleLavender,
  'gitDecoration.deletedResourceForeground':     p.bloodRed,
  'gitDecoration.untrackedResourceForeground':   p.smoke,
  'gitDecoration.ignoredResourceForeground':     alpha(p.mutedPurple, p.opacity.strong),
  'gitDecoration.conflictingResourceForeground': p.bloodRed,
  'gitDecoration.submoduleResourceForeground':   p.warningOrange,

  // settings
  'settings.headerForeground':             p.crtGreen,
  'settings.modifiedItemIndicator':        p.warningOrange,
  'settings.checkboxBackground':           p.shadowPurple,
  'settings.checkboxBorder':               alpha(p.royalPurple, p.opacity.solid),
  'settings.dropdownBackground':           p.shadowPurple,
  'settings.dropdownBorder':               alpha(p.royalPurple, p.opacity.solid),
  'settings.numberInputBackground':        p.shadowPurple,
  'settings.numberInputBorder':            alpha(p.royalPurple, p.opacity.solid),
  'settings.textInputBackground':          p.shadowPurple,
  'settings.textInputBorder':              alpha(p.royalPurple, p.opacity.solid),

  // breadcrumbs
  'breadcrumb.background':                 p.voidBlack,
  'breadcrumb.foreground':                 alpha(p.silver, p.opacity.strong),
  'breadcrumb.focusForeground':            p.crtGreen,
  'breadcrumb.activeSelectionForeground':  p.neonCyan,
  'breadcrumbPicker.background':           p.darkRealm,
};

const darkTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.smoke, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: p.paleLavender } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: p.crtGreen } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: p.neonCyan } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: p.offWhite } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: p.paleLavender, fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.warningOrange } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: p.lightGray } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.bloodRed, background: p.darkRealm } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.smoke, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: p.paleLavender } },
  { scope: ['markup.raw'], settings: { foreground: p.crtGreen } },
  { scope: ['meta.separator'], settings: { foreground: alpha(p.royalPurple, p.opacity.solid), fontStyle: 'bold' } },
  { scope: ['support.class'], settings: { foreground: p.infoBlue } },
  { scope: ['entity.other.inherited-class'], settings: { foreground: p.infoBlue, fontStyle: 'italic' } },
  { scope: ['meta.directive'], settings: { foreground: p.warningOrange } },
  { scope: ['entity.name.tag'], settings: { foreground: p.bloodRed } },
  { scope: ['entity.other.attribute-name'], settings: { foreground: p.crtGreen } },
];

// ---------- LIGHT THEME (fixed) ----------
const lightUi = {
  // editor base
  'editor.background':                     '#FDF9FF',
  'editor.foreground':                     p.deepAbyss,
  'editor.inactiveSelectionBackground':    alpha('#D9C5E6', p.opacity.strong),
  'editor.selectionBackground':            '#8A6AB5',        // darker for 3.0+ contrast
  'editor.selectionHighlightBackground':   alpha('#C5A8D9', p.opacity.light),
  'editor.findMatchBackground':            alpha(p.bloodRed, p.opacity.light),
  'editor.findMatchHighlightBackground':   alpha(p.bloodRed, p.opacity.medium),
  'editor.findRangeHighlightBackground':   alpha('#E8D5F0', p.opacity.medium),
  'editor.lineHighlightBackground':        alpha('#F0E6F5', p.opacity.strong),
  'editor.lineNumber.foreground':          '#6B4E8A',        // darker for 4.5+ contrast
  'editor.lineNumber.activeForeground':    p.deepGreen,
  'editorCursor.foreground':               '#1A6B4A',        // much darker green
  'editorCursor.background':               alpha('#1A6B4A', p.opacity.faint),
  'editorWhitespace.foreground':           alpha('#D9C5E6', p.opacity.medium),
  'editorIndentGuide.background':          alpha('#D9C5E6', p.opacity.light),
  'editorIndentGuide.activeBackground':    '#A188B5',
  'editorBracketMatch.background':         '#D9C5E6',
  'editorBracketMatch.border':             p.bloodRed,
  'editorBracketHighlight.foreground1':    p.deepGreen,
  'editorBracketHighlight.foreground2':    p.infoBlue,
  'editorBracketHighlight.foreground3':    p.warningOrange,
  'editorBracketHighlight.foreground4':    '#A188B5',
  'editorBracketHighlight.unexpectedBracket.foreground': p.bloodRed,
  'editorGutter.background':               '#FDF9FF',
  'editorGutter.modifiedBackground':       alpha(p.infoBlue, p.opacity.medium),
  'editorGutter.addedBackground':          alpha(p.deepGreen, p.opacity.medium),
  'editorGutter.deletedBackground':        alpha(p.bloodRed, p.opacity.medium),
  'editorError.foreground':                p.bloodRed,
  'editorError.border':                    alpha(p.bloodRed, p.opacity.medium),
  'editorWarning.foreground':              p.warningOrange,
  'editorWarning.border':                  alpha(p.warningOrange, p.opacity.medium),
  'editorInfo.foreground':                 p.infoBlue,
  'editorInfo.border':                     alpha(p.infoBlue, p.opacity.medium),
  'editorHint.foreground':                 p.smoke,
  'editorOverviewRuler.errorForeground':   p.bloodRed,
  'editorOverviewRuler.warningForeground': p.warningOrange,
  'editorOverviewRuler.infoForeground':    p.infoBlue,
  'editorOverviewRuler.bracketMatchForeground': '#D9C5E6',
  'editorOverviewRuler.modifiedForeground': alpha(p.infoBlue, p.opacity.strong),
  'editorOverviewRuler.addedForeground':   alpha(p.deepGreen, p.opacity.strong),
  'editorOverviewRuler.deletedForeground': alpha(p.bloodRed, p.opacity.strong),

  // widgets & hovers
  'editorWidget.background':               '#FDF9FF',
  'editorWidget.foreground':               p.deepAbyss,
  'editorWidget.border':                   '#D9C5E6',
  'editorHoverWidget.background':          '#FDF9FF',
  'editorHoverWidget.foreground':          p.deepAbyss,
  'editorHoverWidget.border':              '#D9C5E6',
  'editorSuggestWidget.background':        '#FDF9FF',
  'editorSuggestWidget.foreground':        p.deepAbyss,
  'editorSuggestWidget.selectedBackground': '#8A6AB5',        // match selection
  'editorSuggestWidget.highlightForeground': p.deepGreen,
  'editorSuggestWidget.border':            '#D9C5E6',
  'editorLink.activeForeground':           p.deepGreen,
  'editorLightBulb.foreground':            p.warningOrange,
  'editorLightBulbAutoFix.foreground':     p.deepGreen,

  // diff
  'diffEditor.insertedTextBackground':     alpha(p.deepGreen, p.opacity.light),
  'diffEditor.removedTextBackground':      alpha(p.bloodRed, p.opacity.light),
  'diffEditor.border':                     '#D9C5E6',
  'diffEditor.diagonalFill':               alpha('#D9C5E6', p.opacity.light),

  // lists
  'list.activeSelectionBackground':        '#8A6AB5',        // match selection
  'list.activeSelectionForeground':        p.deepAbyss,
  'list.inactiveSelectionBackground':      '#8A6AB5',        // consistent
  'list.inactiveSelectionForeground':      p.deepAbyss,
  'list.hoverBackground':                  '#F0E6F5',
  'list.hoverForeground':                  p.deepAbyss,
  'list.focusBackground':                  '#D9C5E6',
  'list.focusForeground':                  p.deepAbyss,
  'list.highlightForeground':              p.deepGreen,
  'list.errorForeground':                  p.bloodRed,
  'list.warningForeground':                p.warningOrange,
  'listFilterWidget.background':           '#FDF9FF',
  'listFilterWidget.outline':              p.bloodRed,
  'listFilterWidget.noMatchesOutline':     p.bloodRed,

  // activity bar
  'activityBar.background':                '#FDF9FF',
  'activityBar.foreground':                p.deepAbyss,
  'activityBar.inactiveForeground':        alpha(p.smoke, p.opacity.medium),
  'activityBar.border':                    '#D9C5E6',
  'activityBarBadge.background':           p.bloodRed,
  'activityBarBadge.foreground':           '#FDF9FF',
  'activityBar.activeBorder':              p.deepGreen,
  'activityBar.activeBackground':          alpha('#D9C5E6', p.opacity.light),
  'activityBar.activeFocusBorder':         p.deepGreen,

  // sidebar
  'sideBar.background':                    '#FDF9FF',
  'sideBar.foreground':                    p.deepAbyss,
  'sideBar.border':                        '#D9C5E6',
  'sideBarTitle.foreground':               p.deepGreen,
  'sideBarSectionHeader.background':       '#FDF9FF',
  'sideBarSectionHeader.foreground':       p.deepAbyss,
  'sideBarSectionHeader.border':           '#D9C5E6',
  'sideBar.dropBackground':                alpha('#D9C5E6', p.opacity.medium),

  // status bar
  'statusBar.background':                  '#FDF9FF',
  'statusBar.foreground':                  p.deepAbyss,
  'statusBar.border':                      '#D9C5E6',
  'statusBar.noFolderBackground':          '#FDF9FF',
  'statusBar.debuggingBackground':         p.bloodRed,
  'statusBar.debuggingForeground':         '#FDF9FF',
  'statusBarItem.prominentBackground':     '#D9C5E6',
  'statusBarItem.prominentHoverBackground': '#C5A8D9',
  'statusBarItem.remoteBackground':        p.infoBlue,
  'statusBarItem.remoteForeground':        '#FDF9FF',
  'statusBarItem.errorBackground':         p.bloodRed,
  'statusBarItem.errorForeground':         '#FDF9FF',

  // title bar
  'titleBar.activeBackground':             '#FDF9FF',
  'titleBar.activeForeground':             p.deepAbyss,
  'titleBar.inactiveBackground':           '#FDF9FF',
  'titleBar.inactiveForeground':           alpha(p.smoke, p.opacity.medium),
  'titleBar.border':                       '#D9C5E6',

  // menus
  'menubar.selectionBackground':           '#D9C5E6',
  'menubar.selectionForeground':           p.deepAbyss,
  'menu.background':                       '#FDF9FF',
  'menu.foreground':                       p.deepAbyss,
  'menu.selectionBackground':              '#D9C5E6',
  'menu.selectionForeground':              p.deepAbyss,
  'menu.separatorBackground':              '#D9C5E6',
  'menu.border':                           '#D9C5E6',

  // panel
  'panel.background':                      '#FDF9FF',
  'panel.foreground':                      p.deepAbyss,
  'panel.border':                          '#D9C5E6',
  'panelTitle.activeForeground':           p.deepGreen,
  'panelTitle.activeBorder':               p.deepGreen,
  'panelTitle.inactiveForeground':         alpha(p.smoke, p.opacity.medium),
  'panelInput.border':                     '#D9C5E6',
  'panelSectionHeader.background':         '#FDF9FF',
  'panelSectionHeader.foreground':         p.deepAbyss,
  'panelSectionHeader.border':             '#D9C5E6',

  // inputs
  'input.background':                      '#FDF9FF',
  'input.foreground':                      p.deepAbyss,
  'input.border':                          '#D9C5E6',
  'input.placeholderForeground':           alpha(p.smoke, p.opacity.strong),
  'inputOption.activeBackground':          '#D9C5E6',
  'inputOption.activeBorder':              p.bloodRed,
  'inputOption.hoverBackground':           alpha('#C5A8D9', p.opacity.light),
  'inputValidation.errorBackground':       p.bloodRed,
  'inputValidation.errorForeground':       '#FDF9FF',
  'inputValidation.errorBorder':           p.bloodRed,
  'inputValidation.warningBackground':     p.warningOrange,
  'inputValidation.warningForeground':     '#FDF9FF',
  'inputValidation.warningBorder':         p.warningOrange,
  'inputValidation.infoBackground':        p.infoBlue,
  'inputValidation.infoForeground':        '#FDF9FF',
  'infoBorder': p.infoBlue,

  // scrollbar
  'scrollbar.shadow':                      '#FDF9FF',
  'scrollbarSlider.background':            alpha('#D9C5E6', p.opacity.medium),
  'scrollbarSlider.hoverBackground':       alpha('#C5A8D9', p.opacity.strong),
  'scrollbarSlider.activeBackground':      p.bloodRed,

  // badges & progress
  'badge.background':                      p.bloodRed,
  'badge.foreground':                      '#FDF9FF',
  'progressBar.background':                p.deepGreen,

  // notifications
  'notificationCenterHeader.background':   '#FDF9FF',
  'notificationCenterHeader.foreground':   p.deepAbyss,
  'notificationToast.border':              '#D9C5E6',
  'notifications.background':              '#FDF9FF',
  'notifications.foreground':              p.deepAbyss,
  'notifications.border':                  '#D9C5E6',
  'notificationsErrorIcon.foreground':     p.bloodRed,
  'notificationsWarningIcon.foreground':   p.warningOrange,
  'notificationsInfoIcon.foreground':      p.infoBlue,

  // extensions
  'extensionButton.prominentBackground':       p.bloodRed,
  'extensionButton.prominentForeground':       '#FDF9FF',
  'extensionButton.prominentHoverBackground':  p.darkRed,

  // picker groups
  'pickerGroup.foreground':                p.deepGreen,
  'pickerGroup.border':                    '#D9C5E6',

  // terminal
  'terminal.background':                   '#FDF9FF',
  'terminal.foreground':                   p.deepAbyss,
  'terminal.ansiBlack':                    p.voidBlack,
  'terminal.ansiRed':                      p.bloodRed,
  'terminal.ansiGreen':                    p.deepGreen,
  'terminal.ansiYellow':                   p.warningOrange,
  'terminal.ansiBlue':                     p.infoBlue,
  'terminal.ansiMagenta':                  '#A188B5',
  'terminal.ansiCyan':                     p.neonCyan,
  'terminal.ansiWhite':                    p.offWhite,
  'terminal.ansiBrightBlack':              p.shadowPurple,
  'terminal.ansiBrightRed':                p.bloodRed,
  'terminal.ansiBrightGreen':              p.crtGreen,
  'terminal.ansiBrightYellow':             p.warningOrange,
  'terminal.ansiBrightBlue':               p.infoBlue,
  'terminal.ansiBrightMagenta':            p.royalPurple,
  'terminal.ansiBrightCyan':               p.neonCyan,
  'terminal.ansiBrightWhite':              p.ghostWhite,
  'terminal.selectionBackground':          alpha('#D9C5E6', p.opacity.solid),
  'terminal.dropBackground':               alpha('#D9C5E6', p.opacity.medium),

  // git decorations
  'gitDecoration.addedResourceForeground':       p.deepGreen,
  'gitDecoration.modifiedResourceForeground':    '#A188B5',
  'gitDecoration.deletedResourceForeground':     p.bloodRed,
  'gitDecoration.untrackedResourceForeground':   p.smoke,
  'gitDecoration.ignoredResourceForeground':     alpha('#D9C5E6', p.opacity.strong),
  'gitDecoration.conflictingResourceForeground': p.bloodRed,
  'gitDecoration.submoduleResourceForeground':   p.warningOrange,

  // settings
  'settings.headerForeground':             p.deepGreen,
  'settings.modifiedItemIndicator':        p.warningOrange,
  'settings.checkboxBackground':           '#FDF9FF',
  'settings.checkboxBorder':               '#D9C5E6',
  'settings.dropdownBackground':           '#FDF9FF',
  'settings.dropdownBorder':               '#D9C5E6',
  'settings.numberInputBackground':        '#FDF9FF',
  'settings.numberInputBorder':            '#D9C5E6',
  'settings.textInputBackground':          '#FDF9FF',
  'settings.textInputBorder':              '#D9C5E6',

  // breadcrumbs
  'breadcrumb.background':                 '#FDF9FF',
  'breadcrumb.foreground':                 alpha(p.deepAbyss, p.opacity.strong),
  'breadcrumb.focusForeground':            p.deepGreen,
  'breadcrumb.activeSelectionForeground':  p.deepGreen,
  'breadcrumbPicker.background':           '#FDF9FF',
};

const lightTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.smoke, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: '#A188B5' } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: p.deepGreen } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: p.deepGreen } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: p.deepAbyss } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: '#A188B5', fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.warningOrange } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: p.deepAbyss } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.bloodRed, background: '#FDF9FF' } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.bloodRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.smoke, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: '#A188B5' } },
  { scope: ['markup.raw'], settings: { foreground: p.deepGreen } },
  { scope: ['meta.separator'], settings: { foreground: '#D9C5E6', fontStyle: 'bold' } },
  { scope: ['support.class'], settings: { foreground: p.infoBlue } },
  { scope: ['entity.other.inherited-class'], settings: { foreground: p.infoBlue, fontStyle: 'italic' } },
  { scope: ['meta.directive'], settings: { foreground: p.warningOrange } },
  { scope: ['entity.name.tag'], settings: { foreground: p.bloodRed } },
  { scope: ['entity.other.attribute-name'], settings: { foreground: p.deepGreen } },
];

// ---------- HIGH CONTRAST THEME (unchanged, already perfect) ----------
const hcUi = {
  'editor.background':                     '#000000',
  'editor.foreground':                     '#FFFFFF',
  'editor.inactiveSelectionBackground':    alpha(p.hcYellow, p.opacity.medium),
  'editor.selectionBackground':            p.hcYellow,
  'editor.selectionHighlightBackground':   alpha(p.hcPink, p.opacity.medium),
  'editor.findMatchBackground':            p.hcRed,
  'editor.findMatchHighlightBackground':   alpha(p.hcRed, p.opacity.strong),
  'editor.findRangeHighlightBackground':   alpha(p.hcYellow, p.opacity.light),
  'editor.lineHighlightBackground':        alpha(p.hcYellow, p.opacity.faint),
  'editor.lineNumber.foreground':          p.hcPink,
  'editor.lineNumber.activeForeground':    p.hcGreen,
  'editorCursor.foreground':               p.hcGreen,
  'editorCursor.background':               alpha(p.hcGreen, p.opacity.faint),
  'editorWhitespace.foreground':           alpha(p.hcYellow, p.opacity.strong),
  'editorIndentGuide.background':          p.hcYellow,
  'editorIndentGuide.activeBackground':    p.hcPink,
  'editorBracketMatch.background':         p.hcYellow,
  'editorBracketMatch.border':             p.hcRed,
  'editorBracketHighlight.foreground1':    p.hcGreen,
  'editorBracketHighlight.foreground2':    p.hcCyan,
  'editorBracketHighlight.foreground3':    p.hcPink,
  'editorBracketHighlight.foreground4':    p.hcYellow,
  'editorBracketHighlight.unexpectedBracket.foreground': p.hcRed,
  'editorGutter.background':               '#000000',
  'editorGutter.modifiedBackground':       p.hcCyan,
  'editorGutter.addedBackground':          p.hcGreen,
  'editorGutter.deletedBackground':        p.hcRed,
  'editorError.foreground':                p.hcRed,
  'editorError.border':                    p.hcRed,
  'editorWarning.foreground':              p.hcYellow,
  'editorWarning.border':                  p.hcYellow,
  'editorInfo.foreground':                 p.hcCyan,
  'editorInfo.border':                     p.hcCyan,
  'editorHint.foreground':                 p.lightGray,
  'editorOverviewRuler.errorForeground':   p.hcRed,
  'editorOverviewRuler.warningForeground': p.hcYellow,
  'editorOverviewRuler.infoForeground':    p.hcCyan,
  'editorOverviewRuler.bracketMatchForeground': p.hcYellow,
  'editorOverviewRuler.modifiedForeground': p.hcCyan,
  'editorOverviewRuler.addedForeground':   p.hcGreen,
  'editorOverviewRuler.deletedForeground': p.hcRed,

  'editorWidget.background':               '#000000',
  'editorWidget.foreground':               '#FFFFFF',
  'editorWidget.border':                   p.hcYellow,
  'editorHoverWidget.background':          '#000000',
  'editorHoverWidget.foreground':          '#FFFFFF',
  'editorHoverWidget.border':              p.hcYellow,
  'editorSuggestWidget.background':        '#000000',
  'editorSuggestWidget.foreground':        '#FFFFFF',
  'editorSuggestWidget.selectedBackground': p.hcYellow,
  'editorSuggestWidget.highlightForeground': '#000000',
  'editorSuggestWidget.border':            p.hcYellow,
  'editorLink.activeForeground':           p.hcGreen,
  'editorLightBulb.foreground':            p.hcYellow,
  'editorLightBulbAutoFix.foreground':     p.hcGreen,

  'diffEditor.insertedTextBackground':     alpha(p.hcGreen, p.opacity.light),
  'diffEditor.removedTextBackground':      alpha(p.hcRed, p.opacity.light),
  'diffEditor.border':                     p.hcYellow,
  'diffEditor.diagonalFill':               alpha(p.hcYellow, p.opacity.light),

  'list.activeSelectionBackground':        p.hcYellow,
  'list.activeSelectionForeground':        '#000000',
  'list.inactiveSelectionBackground':      p.hcYellow,
  'list.inactiveSelectionForeground':      '#000000',
  'list.hoverBackground':                  p.hcYellow,
  'list.hoverForeground':                  '#000000',
  'list.focusBackground':                  p.hcYellow,
  'list.focusForeground':                  '#000000',
  'list.highlightForeground':              p.hcGreen,
  'list.errorForeground':                  p.hcRed,
  'list.warningForeground':                p.hcYellow,
  'listFilterWidget.background':           '#000000',
  'listFilterWidget.outline':              p.hcRed,
  'listFilterWidget.noMatchesOutline':     p.hcRed,

  'activityBar.background':                '#000000',
  'activityBar.foreground':                '#FFFFFF',
  'activityBar.inactiveForeground':        p.lightGray,
  'activityBar.border':                    p.hcYellow,
  'activityBarBadge.background':           p.hcRed,
  'activityBarBadge.foreground':           '#000000',
  'activityBar.activeBorder':              p.hcGreen,
  'activityBar.activeBackground':          alpha(p.hcYellow, p.opacity.light),
  'activityBar.activeFocusBorder':         p.hcCyan,

  'sideBar.background':                    '#000000',
  'sideBar.foreground':                    '#FFFFFF',
  'sideBar.border':                        p.hcYellow,
  'sideBarTitle.foreground':               p.hcGreen,
  'sideBarSectionHeader.background':       '#000000',
  'sideBarSectionHeader.foreground':       '#FFFFFF',
  'sideBarSectionHeader.border':           p.hcYellow,
  'sideBar.dropBackground':                alpha(p.hcYellow, p.opacity.medium),

  'statusBar.background':                  '#000000',
  'statusBar.foreground':                  '#FFFFFF',
  'statusBar.border':                      p.hcYellow,
  'statusBar.noFolderBackground':          '#000000',
  'statusBar.debuggingBackground':         p.hcRed,
  'statusBar.debuggingForeground':         '#000000',
  'statusBarItem.prominentBackground':     p.hcYellow,
  'statusBarItem.prominentHoverBackground': p.hcPink,
  'statusBarItem.remoteBackground':        p.hcCyan,
  'statusBarItem.remoteForeground':        '#000000',
  'statusBarItem.errorBackground':         p.hcRed,
  'statusBarItem.errorForeground':         '#000000',

  'titleBar.activeBackground':             '#000000',
  'titleBar.activeForeground':             '#FFFFFF',
  'titleBar.inactiveBackground':           '#000000',
  'titleBar.inactiveForeground':           p.lightGray,
  'titleBar.border':                       p.hcYellow,

  'menubar.selectionBackground':           p.hcYellow,
  'menubar.selectionForeground':           '#000000',
  'menu.background':                       '#000000',
  'menu.foreground':                       '#FFFFFF',
  'menu.selectionBackground':              p.hcYellow,
  'menu.selectionForeground':              '#000000',
  'menu.separatorBackground':              p.hcYellow,
  'menu.border':                           p.hcYellow,

  'panel.background':                      '#000000',
  'panel.foreground':                      '#FFFFFF',
  'panel.border':                          p.hcYellow,
  'panelTitle.activeForeground':           p.hcGreen,
  'panelTitle.activeBorder':               p.hcGreen,
  'panelTitle.inactiveForeground':         p.lightGray,
  'panelInput.border':                     p.hcYellow,
  'panelSectionHeader.background':         '#000000',
  'panelSectionHeader.foreground':         '#FFFFFF',
  'panelSectionHeader.border':             p.hcYellow,

  'input.background':                      '#000000',
  'input.foreground':                      '#FFFFFF',
  'input.border':                          p.hcYellow,
  'input.placeholderForeground':           p.lightGray,
  'inputOption.activeBackground':          p.hcYellow,
  'inputOption.activeBorder':              p.hcRed,
  'inputOption.hoverBackground':           alpha(p.hcYellow, p.opacity.light),
  'inputValidation.errorBackground':       p.hcRed,
  'inputValidation.errorForeground':       '#000000',
  'inputValidation.errorBorder':           p.hcRed,
  'inputValidation.warningBackground':     p.hcYellow,
  'inputValidation.warningForeground':     '#000000',
  'inputValidation.warningBorder':         p.hcYellow,
  'inputValidation.infoBackground':        p.hcCyan,
  'inputValidation.infoForeground':        '#000000',
  'infoBorder': p.hcCyan,

  'scrollbar.shadow':                      '#000000',
  'scrollbarSlider.background':            alpha(p.hcYellow, p.opacity.strong),
  'scrollbarSlider.hoverBackground':       alpha(p.hcPink, p.opacity.solid),
  'scrollbarSlider.activeBackground':      p.hcRed,

  'badge.background':                      p.hcRed,
  'badge.foreground':                      '#000000',
  'progressBar.background':                p.hcGreen,

  'notificationCenterHeader.background':   '#000000',
  'notificationCenterHeader.foreground':   '#FFFFFF',
  'notificationToast.border':              p.hcYellow,
  'notifications.background':              '#000000',
  'notifications.foreground':              '#FFFFFF',
  'notifications.border':                  p.hcYellow,
  'notificationsErrorIcon.foreground':     p.hcRed,
  'notificationsWarningIcon.foreground':   p.hcYellow,
  'notificationsInfoIcon.foreground':      p.hcCyan,

  'extensionButton.prominentBackground':       p.hcRed,
  'extensionButton.prominentForeground':       '#000000',
  'extensionButton.prominentHoverBackground':  p.hcRed,

  'pickerGroup.foreground':                p.hcGreen,
  'pickerGroup.border':                    p.hcYellow,

  'terminal.background':                   '#000000',
  'terminal.foreground':                   '#FFFFFF',
  'terminal.ansiBlack':                    '#000000',
  'terminal.ansiRed':                      p.hcRed,
  'terminal.ansiGreen':                    p.hcGreen,
  'terminal.ansiYellow':                   p.hcYellow,
  'terminal.ansiBlue':                     p.hcCyan,
  'terminal.ansiMagenta':                  p.hcPink,
  'terminal.ansiCyan':                     p.hcCyan,
  'terminal.ansiWhite':                    '#FFFFFF',
  'terminal.ansiBrightBlack':              '#000000',
  'terminal.ansiBrightRed':                p.hcRed,
  'terminal.ansiBrightGreen':              p.hcGreen,
  'terminal.ansiBrightYellow':             p.hcYellow,
  'terminal.ansiBrightBlue':               p.hcCyan,
  'terminal.ansiBrightMagenta':            p.hcPink,
  'terminal.ansiBrightCyan':               p.hcCyan,
  'terminal.ansiBrightWhite':              '#FFFFFF',
  'terminal.selectionBackground':          alpha(p.hcYellow, p.opacity.solid),
  'terminal.dropBackground':               alpha(p.hcYellow, p.opacity.medium),

  'gitDecoration.addedResourceForeground':       p.hcGreen,
  'gitDecoration.modifiedResourceForeground':    p.hcPink,
  'gitDecoration.deletedResourceForeground':     p.hcRed,
  'gitDecoration.untrackedResourceForeground':   p.lightGray,
  'gitDecoration.ignoredResourceForeground':     p.hcYellow,
  'gitDecoration.conflictingResourceForeground': p.hcRed,
  'gitDecoration.submoduleResourceForeground':   p.hcYellow,

  'settings.headerForeground':             p.hcGreen,
  'settings.modifiedItemIndicator':        p.hcYellow,
  'settings.checkboxBackground':           '#000000',
  'settings.checkboxBorder':               p.hcYellow,
  'settings.dropdownBackground':           '#000000',
  'settings.dropdownBorder':               p.hcYellow,
  'settings.numberInputBackground':        '#000000',
  'settings.numberInputBorder':            p.hcYellow,
  'settings.textInputBackground':          '#000000',
  'settings.textInputBorder':              p.hcYellow,

  'breadcrumb.background':                 '#000000',
  'breadcrumb.foreground':                 alpha('#FFFFFF', p.opacity.strong),
  'breadcrumb.focusForeground':            p.hcGreen,
  'breadcrumb.activeSelectionForeground':  p.hcCyan,
  'breadcrumbPicker.background':           '#000000',
};

const hcTokens = [
  { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.lightGray, fontStyle: 'italic' } },
  { scope: ['constant', 'support.constant'], settings: { foreground: p.hcPink } },
  { scope: ['entity.name.function', 'meta.function-call', 'support.function'], settings: { foreground: p.hcGreen } },
  { scope: ['keyword', 'storage', 'storage.type'], settings: { foreground: p.hcRed, fontStyle: 'bold' } },
  { scope: ['string', 'string.quoted', 'string.regexp'], settings: { foreground: p.hcGreen } },
  { scope: ['variable', 'variable.parameter', 'variable.other'], settings: { foreground: '#FFFFFF' } },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type'], settings: { foreground: p.hcPink, fontStyle: 'underline' } },
  { scope: ['constant.numeric', 'constant.language'], settings: { foreground: p.hcRed } },
  { scope: ['punctuation', 'meta.brace'], settings: { foreground: '#FFFFFF' } },
  { scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.hcRed, background: '#000000' } },
  { scope: ['markup.heading', 'entity.name.section'], settings: { foreground: p.hcRed, fontStyle: 'bold' } },
  { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
  { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.quote'], settings: { foreground: p.lightGray, fontStyle: 'italic' } },
  { scope: ['markup.list'], settings: { foreground: p.hcPink } },
  { scope: ['markup.raw'], settings: { foreground: p.hcGreen } },
  { scope: ['meta.separator'], settings: { foreground: p.hcYellow, fontStyle: 'bold' } },
  { scope: ['support.class'], settings: { foreground: p.hcCyan } },
  { scope: ['entity.other.inherited-class'], settings: { foreground: p.hcCyan, fontStyle: 'italic' } },
  { scope: ['meta.directive'], settings: { foreground: p.hcYellow } },
  { scope: ['entity.name.tag'], settings: { foreground: p.hcRed } },
  { scope: ['entity.other.attribute-name'], settings: { foreground: p.hcGreen } },
];

module.exports = {
  dark:  { ui: darkUi, tokens: darkTokens },
  light: { ui: lightUi, tokens: lightTokens },
  highContrast: { ui: hcUi, tokens: hcTokens }
};
